# Generated by Django 2.1.1 on 2018-09-19 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
