# Generated by Django 2.1.1 on 2018-10-04 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0016_userpost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
