# Generated by Django 2.1.1 on 2018-10-04 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0018_auto_20181004_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follow',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
