# Generated by Django 2.1.1 on 2018-10-22 02:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0021_userpost_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grumblr.UserPost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grumblr.UserProfile')),
            ],
        ),
    ]
