# Generated by Django 2.1.1 on 2018-09-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_auto_20180921_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
