# Generated by Django 2.1.1 on 2018-10-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0013_auto_20181002_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empty',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
