# Generated by Django 2.1.1 on 2018-10-19 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0019_auto_20181004_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='intro',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
