# Generated by Django 2.1.1 on 2018-10-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0020_auto_20181019_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
